"""Remove password field, add remote_folder and remote_password

Revision ID: 3c991ef8b34f
Revises: 38b3b4fb85f3
Create Date: 2025-05-19 16:47:00.360248

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3c991ef8b34f"
down_revision = "38b3b4fb85f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("remote_folder", sa.SmallInteger(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("remote_password", sa.String(length=64), nullable=True)
        )
        batch_op.drop_column("password")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password", sa.VARCHAR(length=128), nullable=True)
        )
        batch_op.drop_column("remote_password")
        batch_op.drop_column("remote_folder")

    # ### end Alembic commands ###
