"""User model upgrade for email, password and email confirmation

Revision ID: 694da1b3310d
Revises: ccd7db2ee135
Create Date: 2025-06-30 09:39:14.706957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694da1b3310d'
down_revision = 'ccd7db2ee135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.alter_column('md5_job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('md5_job_finished',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('upload_job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('metadata_study_length',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('metadata_contributors_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('metadata_supplementary_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('metadata_samples_displacement',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('metadata_samples_length',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('metadata_samples_width',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('metadata_protocol_displacement',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('metadata_protocol_length',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('metadata_datasteps_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('metadata_processedfiles_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('metadata_pairedend_displacement',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('email_activation_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('is_email_verified')
        batch_op.drop_column('email_activation_key')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.alter_column('metadata_pairedend_displacement',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('metadata_processedfiles_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('metadata_datasteps_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('metadata_protocol_length',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('metadata_protocol_displacement',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('metadata_samples_width',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('metadata_samples_length',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('metadata_samples_displacement',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('metadata_supplementary_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('metadata_contributors_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('metadata_study_length',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('upload_job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('md5_job_finished',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('md5_job_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
