"""Uploads removed session_sushi_id, is_bulk, remote_folder, remote_passwordand upload_job_finished. Renamed gather_job to md5_job

Revision ID: 9f0c2f3c7ba8
Revises: 3c991ef8b34f
Create Date: 2025-05-19 17:27:48.849766

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9f0c2f3c7ba8"
down_revision = "3c991ef8b34f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("upload_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("md5_job_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("md5_job_finished", sa.Boolean(), nullable=True))
    # Copy data from old columns to new columns (using SQL)
    op.execute(
        "UPDATE upload_sessions SET md5_job_id = gather_job_id WHERE gather_job_id IS NOT NULL"
    )
    op.execute(
        "UPDATE upload_sessions SET md5_job_finished = gather_job_finished WHERE gather_job_finished IS NOT NULL"
    )
    with op.batch_alter_table("upload_sessions", schema=None) as batch_op:
        batch_op.drop_column("gather_job_id")
        batch_op.drop_column("remote_folder")
        batch_op.drop_column("gather_job_finished")
        batch_op.drop_column("session_sushi_id")
        batch_op.drop_column("remote_password")
        batch_op.drop_column("is_bulk")
        batch_op.drop_column("upload_job_finished")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("upload_sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("upload_job_finished", sa.BOOLEAN(), nullable=True)
        )
        batch_op.add_column(sa.Column("is_bulk", sa.BOOLEAN(), nullable=False))
        batch_op.add_column(
            sa.Column("remote_password", sa.VARCHAR(length=64), nullable=False)
        )
        batch_op.add_column(
            sa.Column("session_sushi_id", sa.VARCHAR(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column("gather_job_finished", sa.BOOLEAN(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("remote_folder", sa.VARCHAR(length=64), nullable=False)
        )
        batch_op.add_column(sa.Column("gather_job_id", sa.INTEGER(), nullable=True))

    # Copy data back from new columns to old columns
    op.execute(
        "UPDATE upload_sessions SET gather_job_id = md5_job_id, gather_job_finished = md5_job_finished"
    )

    with op.batch_alter_table("upload_sessions", schema=None) as batch_op:
        batch_op.drop_column("md5_job_finished")
        batch_op.drop_column("md5_job_id")

    # ### end Alembic commands ###
