"""Adding upload_folder to UploadSessionModel

Revision ID: ccd7db2ee135
Revises: 9f0c2f3c7ba8
Create Date: 2025-06-16 18:25:24.001169

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ccd7db2ee135"
down_revision = "9f0c2f3c7ba8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("upload_sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("remote_folder", sa.String(length=64), nullable=True)
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "remote_folder",
            existing_type=sa.SMALLINT(),
            type_=sa.String(length=64),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "remote_folder",
            existing_type=sa.String(length=64),
            type_=sa.SMALLINT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("upload_sessions", schema=None) as batch_op:
        batch_op.drop_column("remote_folder")

    # ### end Alembic commands ###
